# Generated by Django 2.2.1 on 2019-05-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restosearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Restaurant',
        ),
    ]
