# Generated by Django 2.2.1 on 2019-05-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restosearch', '0003_worldborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
