# Generated by Django 2.2.1 on 2019-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restosearch', '0005_restaurant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
