# Generated by Django 2.2.1 on 2019-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restosearch', '0007_auto_20190509_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZomatoCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
