# Generated by Django 2.2.1 on 2019-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restosearch', '0009_auto_20190510_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
